import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'

export async function generateReceipt(payment, org) {
  const doc = new jsPDF({ orientation:'portrait', unit:'mm', format:'a5' })
  const pw  = doc.internal.pageSize.getWidth()
  const currSym = org?.currency_symbol || '$'

  // Colors
  const primary = org?.primary_color || '#15803d'
  const gold    = org?.secondary_color || '#d97706'
  const pr      = parseInt(primary.slice(1,3),16)
  const pg      = parseInt(primary.slice(3,5),16)
  const pb      = parseInt(primary.slice(5,7),16)

  // Header background
  doc.setFillColor(pr, pg, pb)
  doc.rect(0, 0, pw, 38, 'F')

  // Org name
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text(org?.name || 'AMK Circle', pw / 2, 14, { align:'center' })

  // Address
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  const addr = [org?.address, [org?.city, org?.state, org?.country].filter(Boolean).join(', ')].filter(Boolean).join(', ')
  if (addr) doc.text(addr, pw / 2, 20, { align:'center' })
  if (org?.phone) doc.text(`Tel: ${org.phone}`, pw / 2, 25, { align:'center' })
  if (org?.email) doc.text(org.email, pw / 2, 30, { align:'center' })

  // Receipt title
  doc.setFillColor(245, 245, 245)
  doc.rect(0, 38, pw, 12, 'F')
  doc.setTextColor(pr, pg, pb)
  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.text('PAYMENT RECEIPT', pw / 2, 47, { align:'center' })

  // Receipt details
  doc.setTextColor(60, 60, 60)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  let y = 58

  const row = (label, value, bold = false) => {
    doc.setFont('helvetica', 'normal')
    doc.text(label, 12, y)
    doc.setFont('helvetica', bold ? 'bold' : 'normal')
    doc.text(String(value || '—'), pw - 12, y, { align:'right' })
    doc.setDrawColor(220, 220, 220)
    doc.line(12, y + 2, pw - 12, y + 2)
    y += 9
  }

  row('Receipt No.', payment.receipt_number, true)
  row('Date', payment.date)
  row('Payer Name', payment.person_name, true)
  if (payment.person_phone) row('Phone', payment.person_phone)
  if (payment.person_email) row('Email', payment.person_email)
  if (payment.student_name) row('Student', payment.student_name)
  row('Payment Type', payment.payment_type?.replace('_',' ').toUpperCase())
  row('Payment Method', payment.payment_method?.replace('_',' ').toUpperCase())
  if (payment.description) row('Description', payment.description)

  // Amount box
  y += 4
  doc.setFillColor(pr, pg, pb)
  doc.roundedRect(12, y, pw - 24, 18, 3, 3, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.text('AMOUNT PAID', pw / 2, y + 7, { align:'center' })
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(16)
  doc.text(`${currSym}${Number(payment.amount).toLocaleString('en-US', { minimumFractionDigits:2 })}`, pw / 2, y + 14, { align:'center' })
  y += 26

  // Status
  const statusColor = payment.status === 'paid' ? [34,197,94] : payment.status === 'pending' ? [234,179,8] : [239,68,68]
  doc.setFillColor(...statusColor)
  doc.roundedRect(pw/2 - 18, y, 36, 10, 2, 2, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.text(payment.status?.toUpperCase() || 'PAID', pw / 2, y + 7, { align:'center' })
  y += 18

  // Signature line
  doc.setDrawColor(180, 180, 180)
  doc.line(12, y, pw/2 - 8, y)
  doc.line(pw/2 + 8, y, pw - 12, y)
  doc.setTextColor(140, 140, 140)
  doc.setFontSize(7)
  doc.setFont('helvetica', 'normal')
  doc.text('Payer Signature', 12, y + 5)
  doc.text('Authorized Signature', pw/2 + 8, y + 5)
  y += 14

  // Footer
  doc.setFillColor(245, 245, 245)
  doc.rect(0, y, pw, 20, 'F')
  doc.setTextColor(140, 140, 140)
  doc.setFontSize(7)
  doc.text('Thank you for your support. May Allah bless you abundantly.', pw / 2, y + 8, { align:'center' })
  doc.text(`Generated by AMK Circle · amkcircle.com · ${new Date().toLocaleString()}`, pw / 2, y + 14, { align:'center' })

  // Save as file
  const filename = `Receipt-${payment.receipt_number}-${payment.date}.pdf`
  doc.save(filename)
  return filename
}

export async function generateStudentReport(students, org) {
  const doc = new jsPDF({ orientation:'landscape', unit:'mm', format:'a4' })
  const pw  = doc.internal.pageSize.getWidth()

  // Header
  doc.setFillColor(21, 128, 61)
  doc.rect(0, 0, pw, 20, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.text(`${org?.name || 'Organization'} — Student Report`, pw / 2, 13, { align:'center' })

  autoTable(doc, {
    startY: 25,
    head: [['Student ID','Name','Class','Gender','Parent','Phone','Status','Enrolled']],
    body: students.map(s => [s.student_id, s.full_name, s.class_name||'—', s.gender, s.parent_name||'—', s.parent_phone||'—', s.status, s.enrolled_date||'—']),
    headStyles: { fillColor:[21,128,61], textColor:255, fontStyle:'bold', fontSize:8 },
    bodyStyles: { fontSize:8 },
    alternateRowStyles: { fillColor:[240,250,244] },
    margin: { left:10, right:10 },
  })

  doc.save(`Students-Report-${new Date().toISOString().split('T')[0]}.pdf`)
}

export async function generateFinancialReport(payments, summary, org) {
  const doc = new jsPDF({ orientation:'landscape', unit:'mm', format:'a4' })
  const pw  = doc.internal.pageSize.getWidth()
  const currSym = org?.currency_symbol || '$'

  doc.setFillColor(21, 128, 61)
  doc.rect(0, 0, pw, 20, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.text(`${org?.name || 'Organization'} — Financial Report`, pw / 2, 13, { align:'center' })

  // Summary
  autoTable(doc, {
    startY: 25,
    head: [['Payment Type','Count',`Total (${currSym})`]],
    body: summary.map(s => [s.type, s.count, `${currSym}${Number(s.total).toLocaleString()}`]),
    headStyles: { fillColor:[217,119,6], textColor:255 },
    foot: [['Total', summary.reduce((a,b) => a+b.count,0), `${currSym}${summary.reduce((a,b) => a+(b.total||0),0).toLocaleString()}`]],
    footStyles: { fillColor:[21,128,61], textColor:255, fontStyle:'bold' },
    margin: { left:10, right:10 },
  })

  const startY = doc.lastAutoTable.finalY + 8
  autoTable(doc, {
    startY,
    head: [['Receipt','Date','Payer','Type','Method','Amount']],
    body: payments.map(p => [p.receipt_number, p.date, p.person_name, p.payment_type, p.payment_method, `${currSym}${Number(p.amount).toLocaleString()}`]),
    headStyles: { fillColor:[21,128,61], textColor:255, fontSize:8 },
    bodyStyles: { fontSize:7 },
    margin: { left:10, right:10 },
  })

  doc.save(`Financial-Report-${new Date().toISOString().split('T')[0]}.pdf`)
}
